fastfood/fastfood/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = "index"),
    path('food/', include('food.urls', namespace='food')),
]

fastfood/food/urls.py
from django.urls import path
from . import views


app_name = 'food'

urlpatterns = [
    path('pizza',views.pizza, name = "pizzas"),
    path('burger',views.burger, name = "burgers"),
    path('order',views.order, name = "order"),
    path('success',views.success, name = "success"),
    path('signup',views.signup, name = "signup"),
    path('login',views.logIn, name = "login"),
    path('logout',views.logOut, name = "logout"),
]

fastfood/food/models.py
from django.db import models

# Create your models here.


class Pizza(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    pimage = models.URLField()


class Burger(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    bimage = models.URLField()

fastfood/food/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(max_length=100, required=True, help_text='Inform the valid email address')
    class Meta:
        model = User
        fields = ['username' , 'email' , 'first_name' , 'last_name' , 'password1' , 'password2']

fastfood/food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse,JsonResponse
from .models import Pizza, Burger
from .forms import NewUserForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
# Create your views here.

def index(request):
    request.session.set_expiry(0)
    #print(request.session['order'])
    ctx = {'active_link' : 'index'}
    return render(request,"food/index.html",ctx)

def pizza(request):
    request.session.set_expiry(0)
    pizzas = Pizza.objects.all()
    ctx = {'pizzas' : pizzas, 'active_link': 'pizza'}
    return render(request,"food/pizza.html",ctx)

def burger(request):
    request.session.set_expiry(0)
    burgers = Burger.objects.all()
    ctx = {'burgers' : burgers, 'active_link': 'burger'}
    return render(request,"food/burgers.html",ctx)

@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.is_ajax():
        request.session['note'] = request.POST.get('note')
        print(request.session['note'])
        request.session['order'] = request.POST.get('orders')
        print(request.session['order'])
    ctx = {'active-link' : 'order'}
    return render(request,"food/order.html",ctx)


'''
@csrf_exempt
def order(request):
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        test = request.POST.get('test')
        message = request.POST.get('message')
        print(f"Test: {test}, Message: {message}")
        return JsonResponse({'message': 'Data received successfully', 'test': test})
    
    ctx = {'active_link': 'order'}
    return render(request, "food/order.html", ctx)
    '''



def success(request):
    order = request.session['order']
    ctx = {'order' : order}
    return render(request,"food/success.html",ctx)

def signup(request):
    ctx ={}
    if request.POST:
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            ctx['form'] = form
    else:
        form = NewUserForm()
        ctx['form'] = form
    return render(request, 'food/signup.html',ctx)


def logIn(request):
    if request.POST :
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        user = authenticate(request, username=username, password =pwd)
        if user is not None:
            login(request,user)
            return redirect('index')
        else:
            messages.info(request, 'username and/or password are incorect')
    ctx = {'active_link' : 'login'}
    return render(request,'food/login.html',ctx)

def logOut(request):
    logout(request)
    return redirect('index')

fastfood/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}">
    <link rel="icon" href="{% static 'food/images/fast_food_logo.jpg' %}" type="image/x-icon">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'food/images/fast_food_logo.jpg' %}" class="logo" alt="Fast Food Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if active_link == 'index' %}active{% endif %}" aria-current="page"
                            href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if active_link == 'pizza' %}active{% endif %}"
                            href="{% url 'food:pizzas' %}">Pizzas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if active_link == 'burger' %}active{% endif %}"
                            href="{% url 'food:burgers' %}">Burgers</a>
                    </li>
                </ul>
                <form class="d-flex mx-lg-auto mb-2 mb-lg-0" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item mt-2">
                        <h5 class="text-light pt-2 pr-4">Welcome {{ user.username }}</h5>
                    </li>
                    {% endif %}
                    <li class="nav-item mt-2">
                        <a href="{% url 'food:order' %}" class="nav-link {% if active_link == 'order' %}active{% endif %}">
                            <img src="https://img.icons8.com/fluent/30/000000/shopping-cart.png" alt="Cart">
                            <span id="cart"></span>
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'food:logout' %}" class="nav-link {% if active_link == 'logout' %}active{% endif %}">
                            <img src="https://img.icons8.com/windows/24/000000/user.png" alt="" class="bg-light ml-2 rounded-circle">
                            <br>LogOut
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'food:login' %}" class="nav-link {% if active_link == 'login' %}active{% endif %}">
                            <img src="https://img.icons8.com/windows/24/000000/user.png" alt="" class="bg-light ml-2 rounded-circle">
                            <br>LogIn
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div>
        {% block content %} {% endblock %}
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
   
    <script src="{% static 'food/js/main.js' %}"></script>
   
</body>

</html>

fastfood/food/templates/food/burgers.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Burgers{% endblock %}


{% block content %}



<div class="container-fluid">
    <div class="row text-center">
        <div class="col-md-8">
            <h2 class="ttle">Our Burgers</h2>
            <div class="row">
                {% for burger in burgers %}
                <div class="col-md-4 p-4">
                    <img src="{{ burger.bimage }}" alt="" class="picture">
                    <h4 class="pt-3" id="bur{{ burger.id }}">{{ burger.name }}</h4>
                    <div class="form-check-inline">
                        <label for="" class="form-check-label">
                            <input type="radio" class="form-ckeck-input" name="burger{{ burger.id }}" value="{{ burger.priceM }}" checked>
                            M : {{ burger.priceM }}
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label for="" class="form-check-label">
                            <input type="radio" class="form-ckeck-input" name="burger{{ burger.id }}" value="{{ burger.priceM }}">
                            L : {{ burger.priceL }}
                        </label>
                    </div>
                    <div>
                    <button class="btn-info mt-3" onclick="addBurger('{{ burger.id }}')">Add to cart</button>
                </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 orders">
            <div class="bg-dark p-4 rounded text-light">
                <h2 class="text-center">Order List</h2>
                <ul id="bcart"></ul>
                <h4 class="text-right" id="btotal">Total : 0 $</h4>
            </div>
            
        </div>
    </div>
</div>
<script src="{% static 'food/js/borders.js' %}"></script>

{% endblock %}

fastfood/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="home"></div>

{% endblock %}

fastfood/food/templates/food/login.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-6 p-4 bg-dark text-light text-center">
                <h3>Login</h3>
                <a  href="{% url 'food:signup' %}" >Signup</a>
                <form method="POST" class="pt-2">
                    {% csrf_token %}
                   
                        <div class="form-group">
                           <input type="text" name="username" placeholder="Username"> 
                        </div>
                        <div class="form-group">
                            <input type="password" name="password" placeholder="************">
                        </div>
                  
                    {% if messages %}
                        <ul class="pt-2 text-center">
                            {% for msg in messages %}
                                <li style="color: red;"> {{ msg }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <button type="submit" class="btn-info">Login</button>

                </form>
            </div>
            <div class="col-md-3">

            </div>
        </div>
    </div>

{% endblock %}

fastfood/food/templates/food/order.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Order{% endblock %}

{% block content %}
<div class="container-fluid m-4">
    {% if user.is_authenticated %}
    <h2> Welcome {{ user.username}}</h2>
    {% endif %}
    <div class="row">
       
        <div class="col-md-6 text-center">
            <h2>Order</h2>
            <div class="row">
                <div class="col-md-3" id="name">
                    <h3>Name</h3>
                </div>
                <div class="col-md-3" id="size">
                    <h3>Size</h3>
                </div>
                <div class="col-md-3" id="price">
                    <h3>Price</h3>
                </div>
                <div class="col-md-1" id="rm"></div>
            </div>
            <h2 id="total"> Total :</h2>
        </div>
        
        <div class="col-md-5 m-4">
            <h2>Message</h2>
            <textarea name="message" id="messag" cols="40" rows="5"></textarea>
            {% if user.is_authenticated %}
   
            <div class="ml-auto m-4">
                <button type="submit" class="btn btn-success" onclick="order()">Submit</button>
            </div>
            {% else %}
            <div class="ml-auto m-4">
                <a  href="{% url 'food:login' %}">Login</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<script src="{% static 'food/js/cart.js' %}"></script>

{% endblock %}

fastfood/food/templates/food/pizza.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Pizzas{% endblock %}


{% block content %}



<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 text-center">
            <h2 class="title">Our Pizzas</h2>
            <div class="row">
                {% for pizza in pizzas %}
                <div class="col-md-4 p-4">
                    <img src="{{ pizza.pimage }}" alt="" class="picture">
                    <h4 class="pt-3" id="piz{{pizza.id}}">{{ pizza.name }}</h4>
                    <div class="form-check-inline">
                        <label for="" class="form-check-label">
                            <input type="radio" class="form-ckeck-input" name="pizza{{ pizza.id }}" value="{{ pizza.priceM }}" checked>
                            M : {{ pizza.priceM }}
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label for="" class="form-check-label">
                            <input type="radio" class="form-ckeck-input" name="pizza{{ pizza.id }}" value="{{ pizza.priceL }}">
                            L : {{ pizza.priceL }}
                        </label>
                    </div>
                    <div>
                        <button class="btn-info mt-3" onclick="addPizza('{{ pizza.id }}')">Add to cart</button>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 orders">
            <div class="bg-dark p-4 rounded text-light">
            <h2 class="text-center">Order List</h2>
            <ul id="pcart"></ul>
            <h4 class="text-right" id="ptotal">Total : 0 $</h4>
        </div>
        </div>
    </div>
</div>
<script src="{% static 'food/js/order.js' %}"></script>

{% endblock %}

fastfood/food/templates/food/signup.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Signup{% endblock %}

{% block content %}

    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-6 p-4 bg-dark text-light text-center">
                <h3>Signup</h3>
                <a  href="{% url 'food:login' %}" >Login</a>
                <form method="POST" class="pt-2">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <div>
                                {{ field.label_tag }}
                            </div>
                            <div>
                                {{ field }}
                            </div>
                            {% if field.help_text %}

                                <small style="color: gray">{{ field.help_text }}</small>

                            {% endif %}

                            {% for error in form.errors %}

                            {% endfor %}
                        </div>
                    {% endfor %}
                    <small style="color: red">{{ error }}</small>

                    <button type="submit" class="btn-info">Signup</button>

                </form>
            </div>
            <div class="col-md-3">

            </div>
        </div>
    </div>

{% endblock %}

fastfood/food/templates/food/success.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Order Success{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2 text-center">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">We have received your order</h2>
                    <hr>
                    <h4 class="card-text">You have ordered:</h4>
                    <p class="card-text font-weight-bold">{{ order }}</p>
                    <hr>
                    <h4 class="card-text">If you want to modify your order, please call us</h4>
                    <p class="card-text">Phone: <a href="tel:7972353408">797 235 3408</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}